import { test, expect } from "bun:test";
import { main, parseData } from "./lib";

const testInput = 
`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

test("test input", () => {
  expect(main(testInput)).toBe(21);
});

// test("test parser", () => {
//   expect(parseData(testInput)).toEqual([]);
// });

// test("test parser len", () => {
//   expect(parseData(testInput).length).toBe(4);
// });

// test("test parser internal len", () => {
//   expect(parseData(testInput)[0].length).toBe(4);
// });

